theme: jekyll-theme-minimal
title: Elena Civati - Data Science and Bioinformatics
description: Here you can find some projects I developed, mainly while taking Johns Hopkins University specialisations on Coursera
github:
  is_project_page: false

