theme: jekyll-theme-leap-day
title: Elena Civati - Junior Data Scientist and Bioinformatician
description: Here you can find some of the Data Science and Genomic Data Science projects I developed, mainly while taking Coursera's specialisations
