theme: jekyll-theme-leap-day
layout: single
classes: wide
toc: true
title: Elena Civati - Data Science and Bioinformatics
description: Welcome to my portfolio, where I'm proud to share some case studies I've been working on during my learning path in Data Analytics, Data science and Bioinformatics.
github:
  is_project_page: false



